import { Inter } from 'next/font/google'
import './globals.css'
import { Provider } from 'react-redux'
import { Providers } from '@/store/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
    // initialScale: 1,
    // width: "device-width",
    // maximumScale: 1,
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, user-scalable=no" />
            </head>
            <body className={inter.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
